openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /products:
    get:
      responses:
        401:
          description: 'JWT is invalid.'
    post:
      responses:
        400:
          description: 'Bad request.'
        401:
          description: 'JWT is missing or invalid.'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
        required: true
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT