blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/FoalTS/foal/blob/master/.github/CONTRIBUTING.MD#security-vulnerabilities
    about: Report a security vulnerability.